import {basicLesson,generate,generateCloud,lessonPath,validateLesson} from './engine.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='quicklearn.lessons.v2';
let lessons=[],active=null,view='home',mode='paste',file=null,fileText='',uploadToken=0,busy=false,recognition=null,objectURL=null,playToken=0,cardIndex=0,flipped=false;
try{lessons=JSON.parse(localStorage.getItem(KEY)||'null')||JSON.parse(localStorage.getItem('quicklearn.kits.v1')||'[]').map(k=>({...basicLesson(k.text,k.title),id:k.id,text:k.text,sourceLabel:k.sourceLabel,createdAt:k.createdAt,engine:'basic',completed:0,mastered:[]}));}catch{notice('Saved lessons could not be read. Existing browser data has not been overwritten.');}
function notice(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('#toast').style.display='none',5000);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(lessons));return true;}catch{notice('Storage is full. Export a backup before closing this page. Your changes are not saved.');return false;}}
const percent=k=>Math.round((k.completed||0)/lessonPath(k).length*100);
const progress=n=>'<div class="progress-row"><div class="progress"><i style="width:'+n+'%"></i></div><small>'+n+'%</small></div>';
function stopAudio(){playToken++;window.speechSynthesis?.cancel();}
function go(next,id){stopAudio();if(objectURL){URL.revokeObjectURL(objectURL);objectURL=null;}if(id)active=lessons.find(k=>k.id===id);view=active?next:'home';if(next==='home'){view='home';active=null;}document.body.classList.toggle('lesson',view!=='home');$('#rail').hidden=view==='home';$('#crumb').textContent=active?'Home › '+active.title:'';renderRail();({home:home,learn:learn,notes:notes,quiz:quiz,flashcards:flashcards,podcast:podcast,source:source})[view]();window.scrollTo(0,0);}
function renderRail(){const tabs=[['learn','♧','Learn'],['notes','▤','Notes'],['quiz','☑','Quiz'],['flashcards','▢','Flashcards'],['podcast','♬','Podcast'],['source','▧','Source']];$('#rail').innerHTML=tabs.map(([v,i,t])=>'<button data-view="'+v+'" class="'+(view===v?'active':'')+'"><span>'+i+'</span>'+t+'</button>').join('');$('#rail').querySelectorAll('button').forEach(b=>b.onclick=()=>go(b.dataset.view));}
function home(){
 $('#app').innerHTML='<section class="hero"><div class="glyph">✦</div><h1>What do you want to learn?</h1><p class="muted">Your material. A little guidance. A lot of understanding.</p></section><section class="composer"><p>Upload your lecture slides, notes, or a transcript</p><div class="row"><div class="actions">'+[['record','♩ Record'],['file','↑ Upload'],['youtube','▷ YouTube'],['paste','▤ Paste']].map(([m,t])=>'<button data-import="'+m+'">'+t+'</button>').join('')+'</div><button class="primary" data-import="paste" aria-label="Create a lesson">↑</button></div></section><div class="row"><h2>Lessons</h2><div class="actions"><button id="backup">Export backup</button><button id="restore">Import backup</button><input hidden type="file" id="backupFile" accept=".json"></div></div><p class="muted">Saved on this browser. Export a backup to move lessons to another device.</p>'+(lessons.length?lessons.map(k=>'<button class="lesson-card" data-id="'+esc(k.id)+'"><span class="icon">✦</span><span><strong>'+esc(k.title)+'</strong><small>'+esc(k.sourceLabel||'Source material')+' · '+(k.engine==='ai'||k.engine==='cloud'?'AI lesson':'Basic source review')+'</small></span><span class="percent">'+percent(k)+'%</span></button>').join(''):'<div class="empty"><h3>Your next discovery starts here</h3><p class="muted">Add your first source to create a lesson and unlock your study tools.</p></div>');
 document.querySelectorAll('[data-import]').forEach(b=>b.onclick=()=>openImport(b.dataset.import));document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>go('learn',b.dataset.id));
 $('#backup').onclick=()=>download('quicklearn-backup.json',JSON.stringify({version:2,lessons},null,2),'application/json');
 $('#restore').onclick=()=>$('#backupFile').click();$('#backupFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>20000000)throw Error('Backup is too large.');const data=JSON.parse(await f.text());if(data.version!==2||!Array.isArray(data.lessons))throw Error('Invalid backup');const incoming=data.lessons.map(k=>{validateLesson(k);if(typeof k.text!=='string')throw Error('Missing original text');return {...k,id:crypto.randomUUID(),completed:Math.max(0,Math.min(Number(k.completed)||0,lessonPath(k).length)),mastered:Array.isArray(k.mastered)?k.mastered:[],sourceId:null};});lessons.push(...incoming);save();home();notice('Lessons restored. Backups include source text, but not original PDF files.');}catch(e){notice(e.message);}};
}
function learn(){
 const path=lessonPath(active),done=active.completed||0;
 $('#app').innerHTML='<span class="eyebrow">'+(active.engine==='ai'||active.engine==='cloud'?'Your guided learning journey':'Basic source review · not AI-generated')+'</span><h1>'+esc(active.title)+'</h1>'+progress(percent(active))+'<div class="actions"><button class="primary" id="continue">'+(done===path.length?'Review lesson':'Continue →')+'</button><p class="muted">'+(done===path.length?'All stages complete. Well done!':'UP NEXT · '+esc(path[done].title))+'</p></div><div class="row" style="margin-top:45px"><h2>Contents</h2><small>'+done+' of '+path.length+' complete</small></div><ol class="timeline">'+path.map((s,i)=>'<li class="'+(i<done?'done':i===done?'current':'locked')+'"><span class="node">'+(i<done?'✓':s.type==='teach'?i+1:'★')+'</span><div class="stage"><strong>'+esc(s.title)+'</strong><button data-step="'+i+'" '+(i>done?'disabled':'')+'>'+(i<done?'Review':i===done?'Start':'Locked')+'</button></div></li>').join('')+'</ol>';
 $('#continue').onclick=()=>stage(Math.min(done,path.length-1));document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>stage(Number(b.dataset.step)));
}
function stage(index){
 const path=lessonPath(active),s=path[index];if(index>(active.completed||0))return;
 $('#app').innerHTML='<button id="back">← Contents</button><p class="eyebrow">Stage '+(index+1)+' of '+path.length+'</p><h1>'+esc(s.title)+'</h1><div id="teaching"></div><div id="question"></div>';
 $('#back').onclick=learn;
 const finish=()=>{active.completed=Math.max(active.completed||0,index+1);save();learn();};
 if(s.type==='teach'){
  const item=active.stages[s.index];$('#teaching').innerHTML='<div class="reading"><p>'+esc(item.teach)+'</p><h2>Why this matters</h2><p>'+esc(item.why)+'</p><div class="explanation"><strong>Let’s make it concrete</strong><p>'+esc(item.example)+'</p></div></div><button class="primary" id="check">Check my understanding →</button>';
  $('#check').onclick=()=>{$('#check').hidden=true;ask(item.check,$('#question'),finish,true);};
 }else{
  const questions=s.type==='final'?active.quiz:s.indices.map(i=>active.stages[i].check);let n=0;
  const next=()=>{if(n===questions.length){finish();return;}$('#teaching').innerHTML='<p class="muted">Question '+(n+1)+' of '+questions.length+' · answer correctly to continue</p>';ask(questions[n++],$('#question'),next,true);};next();
 }
}
function ask(q,container,next,required=false){
 let selected=null;container.innerHTML='<section class="card"><h2>'+esc(q.question)+'</h2><div class="options">'+q.options.map((o,i)=>'<button class="option" data-answer="'+i+'">'+String.fromCharCode(65+i)+'. '+esc(o)+'</button>').join('')+'</div><div class="feedback" aria-live="polite"></div><button class="primary next" hidden>Continue →</button></section>';
 container.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(selected!==null)return;selected=Number(b.dataset.answer);const correct=selected===q.answer;container.querySelectorAll('[data-answer]').forEach(btn=>{btn.disabled=true;if(Number(btn.dataset.answer)===q.answer)btn.classList.add('correct');else if(btn===b)btn.classList.add('wrong');});container.querySelector('.feedback').innerHTML='<div class="explanation '+(correct?'success':'')+'"><strong>'+(correct?'Exactly right.':'Let’s unpack that.')+'</strong><p>'+esc(q.explanation)+'</p></div>';const nextButton=container.querySelector('.next');nextButton.hidden=false;nextButton.textContent=!correct&&required?'Try again':'Continue →';nextButton.onclick=!correct&&required?()=>ask(q,container,next,required):next;});
}
function notes(){
 $('#app').innerHTML='<span class="eyebrow">'+(active.engine==='ai'||active.engine==='cloud'?'AI-generated notes · check against your source':'Extracted source review')+'</span><h1>'+esc(active.title)+'</h1><div class="actions"><button id="edit">Edit notes</button><button id="exportNotes">Download notes</button></div><article class="notes">'+esc(active.notes)+'</article><div id="editor" hidden><textarea id="notesText" rows="20">'+esc(active.notes)+'</textarea><button id="saveNotes" class="primary">Save notes</button></div><details><summary>Ask about this source</summary><p class="muted">Source search finds matching passages, not an AI chat answer.</p><input id="search" placeholder="Search for a concept"><div id="matches"></div></details>';
 $('#edit').onclick=()=>{$('#editor').hidden=!$('#editor').hidden;$('.notes').hidden=!$('#editor').hidden;};$('#saveNotes').onclick=()=>{active.notes=$('#notesText').value;save();notes();};$('#exportNotes').onclick=()=>download(active.title+'.txt',active.notes);$('#search').oninput=()=>{const words=$('#search').value.toLowerCase().split(/\s+/).filter(w=>w.length>2);$('#matches').innerHTML=words.length?active.text.split(/\n+|(?<=[.!?])\s+/).filter(s=>words.some(w=>s.toLowerCase().includes(w))).slice(0,5).map(s=>'<p class="explanation">'+esc(s)+'</p>').join('')||'<p>No matching source passage found.</p>':'';};
}
function quiz(){
 let n=0,score=0;$('#app').innerHTML='<h1>Test your understanding</h1><div id="quizProgress"></div><div id="quizQuestion"></div>';
 const next=()=>{if(n===active.quiz.length){active.quizScore=score;save();$('#quizQuestion').innerHTML='<div class="card center"><h2>'+score+' / '+n+' correct</h2><p>Every answer is a chance to learn.</p><button id="retry" class="primary">Practice again</button></div>';$('#retry').onclick=quiz;$('#quizProgress').innerHTML=progress(100);return;}$('#quizProgress').innerHTML=progress(Math.round(n/active.quiz.length*100));const q=active.quiz[n++];ask(q,$('#quizQuestion'),next);$('#quizQuestion').querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{if(Number(b.dataset.answer)===q.answer)score++;},{once:true}));};next();
}
function flashcards(){
 active.mastered??=[];cardIndex=0;flipped=false;
 $('#app').innerHTML='<div class="center"><h1>Welcome to Flashcards</h1><p class="muted">Choose how many of your '+active.flashcards.length+' source-based cards to study.</p></div><div class="count">'+[...([5,10,20].filter(n=>n<active.flashcards.length)),'All'].map(n=>'<button data-count="'+n+'">'+n+'</button>').join('')+'</div><div id="deck"></div>';
 document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{cardIndex=0;flipped=false;const deck=active.flashcards.slice(0,b.dataset.count==='All'?undefined:Number(b.dataset.count));document.querySelectorAll('[data-count]').forEach(x=>x.classList.toggle('selected',x===b));draw(deck);});
 function draw(deck){const c=deck[cardIndex];$('#deck').innerHTML='<p class="center muted">Card '+(cardIndex+1)+' of '+deck.length+' · '+active.mastered.length+' marked learned</p><button class="card flash" id="flip">'+esc(flipped?c.back:c.front)+'</button><p class="center muted">Click the card to '+(flipped?'see the question':'reveal the answer')+'</p><div class="row"><button id="prev" '+(cardIndex===0?'disabled':'')+'>← Previous</button><button id="master" class="primary">'+(active.mastered.includes(cardIndex)?'✓ Learned':'Mark learned')+'</button><button id="next" '+(cardIndex===deck.length-1?'disabled':'')+'>Next →</button></div>';$('#flip').onclick=()=>{flipped=!flipped;draw(deck);};$('#prev').onclick=()=>{cardIndex--;flipped=false;draw(deck);};$('#next').onclick=()=>{cardIndex++;flipped=false;draw(deck);};$('#master').onclick=()=>{active.mastered=active.mastered.includes(cardIndex)?active.mastered.filter(i=>i!==cardIndex):[...active.mastered,cardIndex];save();draw(deck);};}
 document.querySelector('[data-count="All"]').click();
}
function podcast(){
 const voices=window.speechSynthesis?.getVoices()||[];
 $('#app').innerHTML='<div class="center"><h1>Listen. Connect. Remember.</h1><p class="muted">A two-speaker conversation about your lesson.</p></div><div class="split">'+[1,2].map(n=>'<label>Speaker '+n+'<select id="voice'+n+'">'+(voices.length?voices.map((v,i)=>'<option value="'+i+'" '+(i===n-1?'selected':'')+'>'+esc(v.name)+' · '+esc(v.lang)+'</option>').join(''):'<option>Default browser voice</option>')+'</select></label>').join('')+'</div><p class="muted">Uses your device’s speech voices. Two distinct voices depend on your browser. This is live playback, not a downloadable audio file.</p><div class="actions"><button class="primary" id="play">▶ Play conversation</button><button id="pause">Pause / resume</button><button id="stop">Stop</button><button id="transcript">Download transcript</button></div><p id="audioStatus" role="status"></p><div class="card">'+active.podcast.map(p=>'<div class="speaker"><strong>Speaker '+p.speaker+'</strong><p>'+esc(p.text)+'</p></div>').join('')+'</div>';
 $('#play').onclick=()=>{if(!window.speechSynthesis){notice('Speech playback is not supported by this browser. Read or download the transcript.');return;}stopAudio();const token=playToken,lines=active.podcast;let i=0;const speak=()=>{if(token!==playToken)return;if(i===lines.length){$('#audioStatus').textContent='Conversation complete';return;}const line=lines[i++],u=new SpeechSynthesisUtterance(line.text);u.voice=voices[Number($('#voice'+line.speaker).value)]||null;u.rate=line.speaker===1?1:.95;u.onend=speak;u.onerror=()=>{if(token===playToken)$('#audioStatus').textContent='Playback stopped. Check browser audio permissions or choose another voice.';};$('#audioStatus').textContent='Speaker '+line.speaker+' · turn '+i+' of '+lines.length;window.speechSynthesis.speak(u);};speak();};
 $('#pause').onclick=()=>{const s=window.speechSynthesis;if(s?.paused)s.resume();else s?.pause();};$('#stop').onclick=()=>{stopAudio();$('#audioStatus').textContent='Stopped';};$('#transcript').onclick=()=>download(active.title+'-podcast.txt',active.podcast.map(p=>'Speaker '+p.speaker+': '+p.text).join('\n\n'));
}
async function source(){
 const current=active;$('#app').innerHTML='<h1>Original source</h1><p class="muted">'+esc(active.sourceLabel)+'</p><div id="original"></div><details open><summary>Extracted text</summary><pre class="card source">'+esc(active.text)+'</pre></details><button id="deleteLesson">Delete this lesson</button>';
 $('#deleteLesson').onclick=async()=>{if(!confirm('Delete this lesson and its progress from this browser?'))return;lessons=lessons.filter(k=>k.id!==current.id);if(save()){await blobStore('delete',current.id).catch(()=>{});go('home');}};
 if(current.sourceId){try{const blob=await blobStore('get',current.id);if(blob&&active===current&&view==='source'){objectURL=URL.createObjectURL(blob);$('#original').innerHTML=(blob.type==='application/pdf'?'<iframe title="Original PDF" class="source-frame" src="'+objectURL+'"></iframe>':'')+'<p><a href="'+objectURL+'" download="'+esc(current.sourceLabel)+'">Download original file</a></p>';}}catch{notice('Original file could not be loaded. Extracted text is still available.');}}
 if(current.sourceURL&&/^https:\/\/(www\.)?(youtube\.com|youtu\.be)\//.test(current.sourceURL))$('#original').insertAdjacentHTML('beforeend','<p><a target="_blank" rel="noopener noreferrer" href="'+esc(current.sourceURL)+'">Open original YouTube video ↗</a></p>');
}
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function blobStore(action,id,value){return new Promise((resolve,reject)=>{const open=indexedDB.open('quicklearn.sources',1);open.onupgradeneeded=()=>open.result.createObjectStore('files');open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,tx=db.transaction('files',action==='get'?'readonly':'readwrite'),store=tx.objectStore('files');const req=action==='get'?store.get(id):action==='put'?store.put(value,id):store.delete(id);tx.oncomplete=()=>{resolve(req.result);db.close();};tx.onerror=()=>{reject(tx.error);db.close();};};});}
function setMode(m){mode=m;stopRecording();$('#filePanel').hidden=m!=='file';$('#youtubePanel').hidden=m!=='youtube';$('#recordPanel').hidden=m!=='record';$('#textLabel').hidden=m==='file';$('#url').required=m==='youtube';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===m));}
function openImport(m){setMode(m);$('#ocrReview').hidden=true;$('#engine').value=location.hostname==='127.0.0.1'||location.hostname==='localhost'?'ai':'cloud';$('#status').textContent=$('#engine').value==='cloud'?'Cloud AI uses your Puter account and free monthly allowance.':'AI generation can take several minutes.';$('#import').showModal();}
function stopRecording(){recognition?.stop();recognition=null;$('#record').textContent='Start recording transcript';}
async function recognizePages(pages,token){
 const {default:Tesseract}=await import('./ocr/tesseract.esm.min.js');const {createWorker,PSM}=Tesseract;
 const worker=await createWorker('eng',1,{workerPath:new URL('./ocr/worker.min.js',import.meta.url).href,corePath:new URL('./ocr/tesseract-core-simd-lstm.wasm.js',import.meta.url).href,langPath:new URL('./ocr/',import.meta.url).href,gzip:true,logger:m=>{if(m.status==='recognizing text'&&token===uploadToken)$('#fileStatus').textContent='Reading handwriting · '+Math.round((m.progress||0)*100)+'%…';}});
  try{await worker.setParameters({tessedit_pageseg_mode:PSM.SPARSE_TEXT});const output=[];for(let i=0;i<pages.length;i++){if(token!==uploadToken)return [];$('#fileStatus').textContent='Reading handwriting · page '+(i+1)+' of '+pages.length+'…';const result=await worker.recognize(pages[i]);output.push(result.data.text.trim());}return output;}finally{await worker.terminate();}
}
async function upload(f){
 const token=++uploadToken;file=null;fileText='';$('#ocrReview').hidden=true;$('#ocrText').value='';$('#fileStatus').textContent='Reading '+f.name+'…';$('#generate').disabled=true;
 try{
  if(!/\.(pdf|txt|md|markdown|png|jpe?g|webp)$/i.test(f.name))throw Error('Use a PDF, TXT, Markdown, PNG, JPG, or WebP file.');
  if(!f.size||f.size>30*1024*1024)throw Error('Choose a non-empty file smaller than 30 MB.');
  let text='',usedOCR=false;
  if(/\.pdf$/i.test(f.name)){
   const pdfjs=await import('./vendor/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.min.mjs',import.meta.url).href;const pdf=await pdfjs.getDocument({data:await f.arrayBuffer()}).promise,pages=[],canvases=[],ocrIndices=[];
    try{if(pdf.numPages>20)throw Error('This PDF has more than 20 pages. Split it into smaller lessons.');for(let n=1;n<=pdf.numPages;n++){if(token!==uploadToken)return;$('#fileStatus').textContent='Reading page '+n+' of '+pdf.numPages+'…';const page=await pdf.getPage(n),content=await page.getTextContent(),pageText=content.items.map(t=>(t.str||'')+(t.hasEOL?'\n':' ')).join('').trim();pages.push(pageText);if(pageText.length<200){const viewport=page.getViewport({scale:2});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;ocrIndices.push(n-1);canvases.push(canvas);}page.cleanup();}if(canvases.length){usedOCR=true;const results=await recognizePages(canvases,token);if(token!==uploadToken)return;ocrIndices.forEach((index,i)=>{if((results[i]||'').trim().length>pages[index].length)pages[index]=results[i].trim();});}text=pages.filter(Boolean).join('\n\n');}finally{await pdf.destroy();}
  }else if(/\.(png|jpe?g|webp)$/i.test(f.name)){usedOCR=true;text=(await recognizePages([f],token))[0]||'';}else text=await f.text();
  if(text.trim().length<40)throw Error(usedOCR?'I could not read enough handwriting. Try a clearer photo, darker pen, or paste a transcript.':'Not enough readable text in this file.');
  if(token!==uploadToken)return;file=f;fileText=text;if(usedOCR){$('#ocrReview').hidden=false;$('#ocrText').value=text;$('#ocrText').oninput=()=>{fileText=$('#ocrText').value;$('#fileStatus').textContent='Handwriting text ready to review · '+fileText.trim().split(/\s+/).length+' words';};}$('#fileStatus').textContent=(usedOCR?'Handwriting read — review the text below':'Ready')+' · '+f.name+' · '+text.trim().split(/\s+/).length+' words';if(!$('#title').value)$('#title').value=f.name.replace(/\.[^.]+$/,'');
 }catch(e){if(token===uploadToken)$('#fileStatus').textContent=e.name==='PasswordException'?'This PDF is password protected. Unlock it first.':e.message;}finally{if(token===uploadToken)$('#generate').disabled=false;}
}
$('#home').onclick=()=>go('home');$('#close').onclick=()=>{if(!busy){stopRecording();$('#import').close();}};$('#import').addEventListener('cancel',e=>{if(busy)e.preventDefault();else stopRecording();});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#file').onchange=e=>{if(e.target.files[0])upload(e.target.files[0]);};$('#drop').ondragover=e=>e.preventDefault();$('#drop').ondrop=e=>{e.preventDefault();if(!busy&&e.dataTransfer.files[0])upload(e.dataTransfer.files[0]);};
$('#record').onclick=()=>{if(recognition){stopRecording();return;}const API=window.SpeechRecognition||window.webkitSpeechRecognition;if(!API){notice('Live transcription is unavailable here. Paste a transcript instead.');return;}recognition=new API();recognition.continuous=true;recognition.interimResults=false;recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++)$('#text').value+=' '+e.results[i][0].transcript;};recognition.onerror=e=>notice('Microphone: '+e.error+'. You can paste a transcript instead.');recognition.onend=()=>{recognition=null;$('#record').textContent='Start recording transcript';};recognition.start();$('#record').textContent='Stop recording transcript';};
$('#create').onsubmit=async e=>{
 e.preventDefault();if(busy)return;stopRecording();const text=(mode==='file'?fileText:$('#text').value).trim();if(mode==='file'&&!file){$('#status').textContent='Upload a readable file first.';return;}const minLength=$('#engine').value==='ai'?120:40;if(text.length<minLength){$('#status').textContent='Add at least '+minLength+' characters of source material.';return;}
 if(mode==='youtube'&&!/^https:\/\/(www\.)?(youtube\.com|youtu\.be)\//.test($('#url').value)){ $('#status').textContent='Enter a valid YouTube URL.';return;}
 busy=true;$('#create').querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=true);$('#status').classList.remove('error');$('#status').textContent='Building your lesson… This can take several minutes. Keep this window open.';
 try{const engine=$('#engine').value,title=$('#title').value.trim(),data=engine==='ai'?await generate(text,title):engine==='cloud'?await generateCloud(text,title):basicLesson(text,title);const lesson={...data,title:title||data.title,id:crypto.randomUUID(),text,engine,createdAt:new Date().toISOString(),sourceLabel:mode==='file'?file.name:mode==='youtube'?'YouTube transcript':mode==='record'?'Recorded transcript':'Pasted material',sourceURL:mode==='youtube'?$('#url').value:null,completed:0,mastered:[]};if(mode==='file'){await blobStore('put',lesson.id,file);lesson.sourceId=lesson.id;}lessons.unshift(lesson);if(!save()){lessons.shift();throw Error('Lesson could not be saved. Free browser storage and retry.');}$('#import').close();$('#create').reset();file=null;fileText='';$('#fileStatus').textContent='Choose a file to begin.';go('learn',lesson.id);notice('Your lesson is ready.');}catch(error){$('#status').classList.add('error');$('#status').textContent=error.message+' Your source is still here; you can retry or choose Basic source review.';}finally{busy=false;$('#create').querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=false);}
};
// Retire the old cache-first worker so updates and AI requests never use stale assets.
if('serviceWorker' in navigator)navigator.serviceWorker.getRegistrations().then(rs=>rs.filter(r=>r.scope===new URL('./',location.href).href).forEach(r=>r.unregister()));
go('home');
